"""initial schema

Revision ID: aca022e0d307
Revises: 
Create Date: 2026-03-07 06:00:11.400208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca022e0d307'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_runs_collector_name'), 'collector_runs', ['collector_name'], unique=False)
    op.create_index(op.f('ix_collector_runs_started_at'), 'collector_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collector_runs_status'), 'collector_runs', ['status'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('chain_id', sa.String(length=120), nullable=True),
    sa.Column('chain_type', sa.String(length=50), nullable=True),
    sa.Column('base_denom', sa.String(length=50), nullable=True),
    sa.Column('display_denom', sa.String(length=50), nullable=True),
    sa.Column('exponent', sa.Integer(), nullable=True),
    sa.Column('coingecko_id', sa.String(length=120), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_chain_id'), 'networks', ['chain_id'], unique=False)
    op.create_index(op.f('ix_networks_name'), 'networks', ['name'], unique=True)
    op.create_table('network_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_endpoints_network_id'), 'network_endpoints', ['network_id'], unique=False)
    op.create_table('network_status_current',
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('validator_status', sa.String(length=20), nullable=True),
    sa.Column('endpoint_status', sa.String(length=20), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=True),
    sa.Column('snapshot_status', sa.String(length=20), nullable=True),
    sa.Column('governance_status', sa.String(length=20), nullable=True),
    sa.Column('reward_status', sa.String(length=20), nullable=True),
    sa.Column('overall_status', sa.String(length=20), nullable=True),
    sa.Column('local_height', sa.Integer(), nullable=True),
    sa.Column('reference_height', sa.Integer(), nullable=True),
    sa.Column('sync_diff', sa.Integer(), nullable=True),
    sa.Column('active_alerts_count', sa.Integer(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('network_id')
    )
    op.create_index(op.f('ix_network_status_current_endpoint_status'), 'network_status_current', ['endpoint_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_governance_status'), 'network_status_current', ['governance_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_last_updated_at'), 'network_status_current', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_network_status_current_overall_status'), 'network_status_current', ['overall_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_reward_status'), 'network_status_current', ['reward_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_snapshot_status'), 'network_status_current', ['snapshot_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_sync_status'), 'network_status_current', ['sync_status'], unique=False)
    op.create_index(op.f('ix_network_status_current_validator_status'), 'network_status_current', ['validator_status'], unique=False)
    op.create_table('snapshot_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_path', sa.String(length=500), nullable=False),
    sa.Column('filename_pattern', sa.String(length=200), nullable=True),
    sa.Column('compression_type', sa.String(length=50), nullable=True),
    sa.Column('min_expected_size_bytes', sa.Integer(), nullable=True),
    sa.Column('max_age_hours', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_targets_network_id'), 'snapshot_targets', ['network_id'], unique=False)
    op.create_table('validators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('moniker', sa.String(length=200), nullable=True),
    sa.Column('operator_address', sa.String(length=200), nullable=False),
    sa.Column('delegator_address', sa.String(length=200), nullable=True),
    sa.Column('consensus_address', sa.String(length=200), nullable=True),
    sa.Column('is_main', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'operator_address', name='uq_validator_network_operator')
    )
    op.create_index(op.f('ix_validators_network_id'), 'validators', ['network_id'], unique=False)
    op.create_index(op.f('ix_validators_operator_address'), 'validators', ['operator_address'], unique=False)
    op.create_table('endpoint_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('remote_height', sa.Integer(), nullable=True),
    sa.Column('chain_id_reported', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['network_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_checks_checked_at'), 'endpoint_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_endpoint_checks_endpoint_id'), 'endpoint_checks', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_endpoint_checks_status'), 'endpoint_checks', ['status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('validator_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('event_key', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['validator_id'], ['validators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_key'), 'events', ['event_key'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_first_seen_at'), 'events', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_events_last_seen_at'), 'events', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_events_network_id'), 'events', ['network_id'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_validator_id'), 'events', ['validator_id'], unique=False)
    op.create_table('snapshot_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_target_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.String(length=700), nullable=True),
    sa.Column('file_exists', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_mtime', sa.DateTime(), nullable=True),
    sa.Column('age_seconds', sa.Integer(), nullable=True),
    sa.Column('size_delta_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_target_id'], ['snapshot_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_checks_checked_at'), 'snapshot_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_snapshot_checks_snapshot_target_id'), 'snapshot_checks', ['snapshot_target_id'], unique=False)
    op.create_index(op.f('ix_snapshot_checks_status'), 'snapshot_checks', ['status'], unique=False)
    op.create_table('validator_status_current',
    sa.Column('validator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('in_active_set', sa.Integer(), nullable=True),
    sa.Column('jailed', sa.Integer(), nullable=True),
    sa.Column('tombstoned', sa.Integer(), nullable=True),
    sa.Column('tokens', sa.String(length=100), nullable=True),
    sa.Column('delegator_shares', sa.String(length=100), nullable=True),
    sa.Column('commission_rate', sa.String(length=50), nullable=True),
    sa.Column('commission_max_rate', sa.String(length=50), nullable=True),
    sa.Column('commission_max_change_rate', sa.String(length=50), nullable=True),
    sa.Column('min_self_delegation', sa.String(length=100), nullable=True),
    sa.Column('self_delegation_amount', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('voting_power', sa.String(length=100), nullable=True),
    sa.Column('last_seen_height', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['validator_id'], ['validators.id'], ),
    sa.PrimaryKeyConstraint('validator_id')
    )
    op.create_index(op.f('ix_validator_status_current_last_checked_at'), 'validator_status_current', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_validator_status_current_status'), 'validator_status_current', ['status'], unique=False)
    op.create_table('validator_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validator_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('in_active_set', sa.Integer(), nullable=True),
    sa.Column('jailed', sa.Integer(), nullable=True),
    sa.Column('tombstoned', sa.Integer(), nullable=True),
    sa.Column('tokens', sa.String(length=100), nullable=True),
    sa.Column('commission_rate', sa.String(length=50), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('voting_power', sa.String(length=100), nullable=True),
    sa.Column('last_seen_height', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['validator_id'], ['validators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validator_status_history_collected_at'), 'validator_status_history', ['collected_at'], unique=False)
    op.create_index(op.f('ix_validator_status_history_validator_id'), 'validator_status_history', ['validator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validator_status_history_validator_id'), table_name='validator_status_history')
    op.drop_index(op.f('ix_validator_status_history_collected_at'), table_name='validator_status_history')
    op.drop_table('validator_status_history')
    op.drop_index(op.f('ix_validator_status_current_status'), table_name='validator_status_current')
    op.drop_index(op.f('ix_validator_status_current_last_checked_at'), table_name='validator_status_current')
    op.drop_table('validator_status_current')
    op.drop_index(op.f('ix_snapshot_checks_status'), table_name='snapshot_checks')
    op.drop_index(op.f('ix_snapshot_checks_snapshot_target_id'), table_name='snapshot_checks')
    op.drop_index(op.f('ix_snapshot_checks_checked_at'), table_name='snapshot_checks')
    op.drop_table('snapshot_checks')
    op.drop_index(op.f('ix_events_validator_id'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_network_id'), table_name='events')
    op.drop_index(op.f('ix_events_last_seen_at'), table_name='events')
    op.drop_index(op.f('ix_events_first_seen_at'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_key'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_endpoint_checks_status'), table_name='endpoint_checks')
    op.drop_index(op.f('ix_endpoint_checks_endpoint_id'), table_name='endpoint_checks')
    op.drop_index(op.f('ix_endpoint_checks_checked_at'), table_name='endpoint_checks')
    op.drop_table('endpoint_checks')
    op.drop_index(op.f('ix_validators_operator_address'), table_name='validators')
    op.drop_index(op.f('ix_validators_network_id'), table_name='validators')
    op.drop_table('validators')
    op.drop_index(op.f('ix_snapshot_targets_network_id'), table_name='snapshot_targets')
    op.drop_table('snapshot_targets')
    op.drop_index(op.f('ix_network_status_current_validator_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_sync_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_snapshot_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_reward_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_overall_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_last_updated_at'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_governance_status'), table_name='network_status_current')
    op.drop_index(op.f('ix_network_status_current_endpoint_status'), table_name='network_status_current')
    op.drop_table('network_status_current')
    op.drop_index(op.f('ix_network_endpoints_network_id'), table_name='network_endpoints')
    op.drop_table('network_endpoints')
    op.drop_index(op.f('ix_networks_name'), table_name='networks')
    op.drop_index(op.f('ix_networks_chain_id'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_collector_runs_status'), table_name='collector_runs')
    op.drop_index(op.f('ix_collector_runs_started_at'), table_name='collector_runs')
    op.drop_index(op.f('ix_collector_runs_collector_name'), table_name='collector_runs')
    op.drop_table('collector_runs')
    # ### end Alembic commands ###
